### ISSUE TITLE
GoogleCredential.getApplicationDefault() cannot access metadata host in container environment

### ISSUE THREAD

**Issue by toots** [google/google-api-java-client#1003]
When using `GoogleCredential.getApplicationDefault()` in an app running inside a docker container, the default credentials cannot be fetched from the metadata server because its shorthand `metadata` host/domain name is not defined, resulting in the following error:

> UnknownHostException metadata  java.net.AbstractPlainSocketImpl.connect (AbstractPlainSocketImpl.java:184)

This solves the issue inside the docker image:

```
echo "169.254.169.254 metadata" >> /etc/hosts
```

However, the API is described such that the API client user should not have to mind about these details. Therefore, the API client code should be updated to be able to handle this type of situation transparently..

**Comment by chingor13** [comment]
This should no longer be an issue. The default metadata server uses the IP address directly to avoid DNS issues.
