### ISSUE TITLE
How can I use it with Rx Java ?

### ISSUE THREAD

**Issue by yogeshmadaan100** [google/google-api-java-client#1006]
I am trying to use the api client with rx java but stucked. Can you help?

**Comment by Laimiux** [comment]
You would need to write Rx java wrappers around the google api client. What particular example would you like to know? Maybe I can help you out

**Comment by PedroDava** [comment]
@Laimiux   Im trying to use rxjs to make Gapi calls thats a "snap" of my code can u gimme some help?
      function listData(){
        
        Rx.Observable.fromPromise(list()).subscribe(
         function(x){
           console.log(x);
         },
         function(err){
           console.log(err);
         },
        function(){
          console.log("completed");
        });
        
        function list(){
           gapi.client.****.****.list().execute();  
        }

**Comment by Laimiux** [comment]
@PedroDava I'm not familiar with the javascript side of rx and google apis, so I'm not sure if I can be helpful. 

From quick look into it, it seems that google api provides something similar to a promise, but not quite.
https://developers.google.com/api-client-library/javascript/reference/referencedocs#gapiclientrequest

You might need to use Rx.Observable.create 
https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/create.md
where you will create google api request and delegate the response to observer passed in the create method

**Comment by PedroDava** [comment]
@Laimiux  Managed to  make the call using rxjs. thnk you  

  Rx.Observable.fromPromise(
          function (){
            return   gapi.client.*****.*****.list()
              .then(
              function(response){ 
                return response;
              },
              function(err){
                return err;
            });
        }).subscribe(
        function(x){  
          console.log(x);
        },
        function(err){
          console.log(err);
        },
         
        function()
        {console.log("Success");
        });

**Comment by PedroDava** [comment]
callCinemas:function(){
       
        Rx.Observable.fromPromise(
          function (){
            return   gapi.client.***.***.list()
              .then(
              function(response){ 
                return response;
              },
              function(err){
                return err;
            });
        })
          .subscribe(
        function(x){  
          console.log(x);
        },
        function(err){
          console.log(err);
        },
         
        function()
        {console.log("Success");
        });
        
      },
      

@Laimiux  thnk you managed to make the request work....

**Comment by mattwhisenhunt** [comment]
It looks like a member of our great community answered your questions. Thanks Community! Please feel free to reopen if you have any more questions.
