### ISSUE TITLE
Directory API - Users.patch - Unable to clear phones value

### ISSUE THREAD

**Issue by NicolaSpreafico** [google/google-api-java-client#1017]
Hello,

I'm using the [`users.patch`](https://developers.google.com/admin-sdk/directory/v1/reference/users/patch) method with the Java API Client (`rev68-1.21.0`) and I'm unable to clear the phones field due to its nature of list and not single field.

As already explained in the [documentation](https://developers.google.com/admin-sdk/directory/v1/guides/performance#patch), 

> To delete a field, specify the field and set it to null. For example, "comment": null. You can also delete an entire object (if it is mutable) by setting it to null. If you are using the Java API Client Library, use Data.NULL_STRING instead; for details, see JSON null.

to delete a field, with the Java API library, it is required to use `Data.NULLXX` variables (the correct one for each type), but for a list type there is no proper variable.

I tried to set the variabile to `null`or leave an `empty list` but there is no update on that field.

```
User user = new User();
user.setPhones(Data.NULL_STRING);
Directory.Users.Patch request = service.users().patch(userKey, user);
request.execute();
```

```
User user = new User();
user.setPhones(null);
Directory.Users.Patch request = service.users().patch(userKey, user);
request.execute();
```

```
User user = new User();
user.setPhones(Collections.emptyList());
Directory.Users.Patch request = service.users().patch(userKey, user);
request.execute();
```

but the values is always there and not removed.
Which is proper way to clear a List value field?

Inside the [API Explorer](https://developers.google.com/admin-sdk/directory/v1/reference/users/patch#response) there is the proper function to remove the data, and set the field explictly to `null`, but how to reproduce the behaviour with the Java Library?

**Comment by NicolaSpreafico** [comment]
Here is a simple main which I used to try differents methods

```
GoogleCredential credential = GoogleApiManager.createCredential(json);
Builder builder = new Directory.Builder(new NetHttpTransport(), new JacksonFactory(), credential);
Directory build = builder.build();

com.google.api.services.admin.directory.model.User googleUser = build.users().get("user@example.com").execute();
LOG.info("Current value for phone: " + googleUser.getPhones());

com.google.api.services.admin.directory.model.User patch = new com.google.api.services.admin.directory.model.User();
######

com.google.api.services.admin.directory.model.User updatedUser = build.users().patch("user@example.com", patch).execute();
LOG.info("Value for phone after patch call: " + updatedUser.getPhones());

googleUser = build.users().get("user@example.com").execute();
LOG.info("Current value for phone: " + googleUser.getPhones());
```
The `######` line is the one wher I set the phones value, and here is all the attempts

`patch.setPhones(null);`
```
INFORMAZIONI: Current value for phone: [{value=456710, type=mobile}, {value=452611, type=work}]
INFORMAZIONI: Value for phone after patch call: [{value=456710, type=mobile}, {value=452611, type=work}]
INFORMAZIONI: Current value for phone: [{value=456710, type=mobile}, {value=452611, type=work}]
```

`patch.setPhones(Collections.EMPTY_LIST);`
```
INFORMAZIONI: Current value for phone: [{value=456710, type=mobile}, {value=452611, type=work}]
INFORMAZIONI: Value for phone after patch call: [{value=456710, type=mobile}, {value=452611, type=work}]
INFORMAZIONI: Current value for phone: [{value=456710, type=mobile}, {value=452611, type=work}]
```

`patch.setPhones(Data.NULL_STRING);`
```
INFORMAZIONI: Current value for phone: [{value=456710, type=mobile}, {value=452611, type=work}]
INFORMAZIONI: Value for phone after patch call: [{value=456710, type=mobile}, {value=452611, type=work}]
INFORMAZIONI: Current value for phone: [{value=456710, type=mobile}, {value=452611, type=work}]
```

As you can see, different values are unable to clear the `phones` value from the User object

**Comment by NicolaSpreafico** [comment]
I did an intense debugging session getting inside the Java API Client library to found the exact part which is responsible to convert the Java object to raw json for the http payload

I found the section in `com.google.api.client.json.JsonGenerator` at line `160`
I also found [the way](https://developers.google.com/api-client-library/java/google-http-java-client/transport#logging) to enable the full dump of the http connection

With the line
`patch.setPhones(Data.NULL_STRING);`
the http connection seems to be properly made
```
Total: 15 bytes
{"phones":null}
-------------- REQUEST  --------------
POST https://www.googleapis.com/admin/directory/v1/users/utente1@noovle.info
Accept-Encoding: gzip
Authorization: <Not Logged>
User-Agent: Google-API-Java-Client Google-HTTP-Java-Client/1.22.0 (gzip)
x-http-method-override: PATCH
Content-Type: application/json; charset=UTF-8
Content-Encoding: gzip
Content-Length: 35

curl -v --compressed -X POST -H 'Accept-Encoding: gzip' -H 'Authorization: <Not Logged>' -H 'User-Agent: Google-API-Java-Client Google-HTTP-Java-Client/1.22.0 (gzip)' -H 'x-http-method-override: PATCH' -H 'Content-Type: application/json; charset=UTF-8' -H 'Content-Encoding: gzip' -d '@-' -- 'https://www.googleapis.com/admin/directory/v1/users/utente1@noovle.info' << $$$
Total: 15 bytes
{"phones":null}
-------------- RESPONSE --------------
HTTP/1.1 200 OK
ETag: "XRsypGOPUmlmxokHB51cC07Vb3s/-1GD8_1qkjfMUZCC0PU_6Ug8MAc"
Expires: Mon, 01 Jan 1990 00:00:00 GMT
X-XSS-Protection: 1; mode=block
Alternate-Protocol: 443:quic
Server: GSE
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
Alt-Svc: quic=":443"; ma=2592000; v="34,33,32,31,30,29,28,27,26,25"
Date: Sat, 02 Jul 2016 17:32:23 GMT
Vary: X-Origin
Vary: Origin
Transfer-Encoding: chunked
Content-Encoding: gzip
Content-Type: application/json; charset=UTF-8

Total: 1.105 bytes
{
.....
 "phones": [
  {
   "value": "123 stella",
   "type": "work"
  }
 ],
.....
}
```

As you can see the payload is properly created `{"phones":null}`, but the field value still remains in the response.

In the same way, if I use the `patch.setPhones(Collections.emptyList())` line, the payload is configured correctly with an empty array
```
Total: 13 bytes
{"phones":[]}
-------------- REQUEST  --------------
POST https://www.googleapis.com/admin/directory/v1/users/utente1@noovle.info
Accept-Encoding: gzip
Authorization: <Not Logged>
User-Agent: Google-API-Java-Client Google-HTTP-Java-Client/1.22.0 (gzip)
x-http-method-override: PATCH
Content-Type: application/json; charset=UTF-8
Content-Encoding: gzip
Content-Length: 33

curl -v --compressed -X POST -H 'Accept-Encoding: gzip' -H 'Authorization: <Not Logged>' -H 'User-Agent: Google-API-Java-Client Google-HTTP-Java-Client/1.22.0 (gzip)' -H 'x-http-method-override: PATCH' -H 'Content-Type: application/json; charset=UTF-8' -H 'Content-Encoding: gzip' -d '@-' -- 'https://www.googleapis.com/admin/directory/v1/users/utente1@noovle.info' << $$$
Total: 13 bytes
{"phones":[]}
-------------- RESPONSE --------------
HTTP/1.1 200 OK
ETag: "XRsypGOPUmlmxokHB51cC07Vb3s/-1GD8_1qkjfMUZCC0PU_6Ug8MAc"
Expires: Mon, 01 Jan 1990 00:00:00 GMT
X-XSS-Protection: 1; mode=block
Alternate-Protocol: 443:quic
Server: GSE
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
Alt-Svc: quic=":443"; ma=2592000; v="34,33,32,31,30,29,28,27,26,25"
Date: Sat, 02 Jul 2016 17:39:28 GMT
Vary: X-Origin
Vary: Origin
Transfer-Encoding: chunked
Content-Encoding: gzip
Content-Type: application/json; charset=UTF-8

Total: 1.105 bytes
{
 ...
 "phones": [
  {
   "value": "123 stella",
   "type": "work"
  }
 ],
 ...
}
```
but the result is the same, the value is still intact after the API call.

At this point I don't know how which is the problem, considering that the `null` value is sent correctly

**Comment by mattwhisenhunt** [comment]
It sounds like this could be a bug in the API have you tried to reproduce it in [API Explorer](https://developers.google.com/apis-explorer/#p/)?

**Comment by mattwhisenhunt** [comment]
Thank you for filing this issue. We asked some clarifying questions a week or more ago and never heard back from you. We are unable to proceed with this issue until then, so we are closing it. Please feel free to comment with more information and we will re-open this issue.
