### ISSUE TITLE
Java Directory API Issue - special characters on Directory.users.list() throws "Invalid Input: query"

### ISSUE THREAD

**Issue by jayanoop2003** [google/google-api-java-client#1020]
Directory API user search throws IO exception, when the query filter has special characters in it.

**Code:**

 Users result = service.users().list()
                .setDomain("gmail.com")
                .setQuery("email:" + anoop.sadas'ivan@gmail.com)
                .execute();

**Error Message:**

{
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "invalid",
    "message": "Invalid Input: query"
   }
  ],
  "code": 400,
  "message": "Invalid Input: query"
 }
}

Do we have any standard solution to use filter with special characters?

**Comment by mattwhisenhunt** [comment]
This issue may no longer be relevant due to its age. Feel free to re-open.
