### ISSUE TITLE
Browser opening fails silently if Desktop.isDesktopSupported() is false or no default browser is configured

### ISSUE THREAD

**Issue by liamsharp** [google/google-api-java-client#1021]
`AuthorizationCodeInstalledApp.browse(url)` fails silently if `Desktop.isDesktopSupported()` returns false.

The application I'm working on uses this code to give grant users access to Google Analytics, but as the browser doesn't open, they can't authenticate.

To help diagnose this easier, it would be nice to log a warning here, rather than fail silently

To help us work around this in our application it would be nice to return the authorisation url when things fail. Currently we just see the url in our logs, and have to ask users to dig it out from there.

It would be great if the code could try to work around this somehow (try out common browsers using exec perhaps?)

**Comment by mattwhisenhunt** [comment]
This issue may no longer be relevant due to its age. Feel free to re-open.

**Comment by chingor13** [comment]
google-oauth-java-client 1.25.0 added a `AuthorizationCodeInstalledApp.Browser` interface to let you customize the browse behavior. If this is insufficient, please open an issue in that [repository](https://github.com/google/google-oauth-java-client/issues).
