### ISSUE TITLE
Storage's ObjectAccessControls.getItems returns List<Object>

### ISSUE THREAD

**Issue by mziccard** [google/google-api-java-client#1022]
As per title, [`ObjectAccessControls.getItems`](https://developers.google.com/resources/api-libraries/documentation/storage/v1/java/latest/com/google/api/services/storage/model/ObjectAccessControls.html#getItems%28%29) returns a `List<Object>`. I would expect it to return a `List<ObjectAccessControl>` instead.

For reference, the same method for buckets [`BucketAccessControls.getItems`](https://developers.google.com/resources/api-libraries/documentation/storage/v1/java/latest/com/google/api/services/storage/model/BucketAccessControls.html#getItems%28%29) correctly returns a `List<ObjectAccessControl>`.

Is there a reason for this? If not, could you fix? /cc @capstan

**Comment by Capstan** [comment]
Looks like this is a discovery doc oddity. I'll file an internal bug.

**Comment by Capstan** [comment]
v1-rev85-1.22.0 fixes this.
