### ISSUE TITLE
Duplicate link present for 'Content API for Shopping' at "https://developers.google.com/products/"

### ISSUE THREAD

**Issue by komalbhimani** [google/google-api-java-client#1024]
Duplicate link present for 'Content API for Shopping' at "https://developers.google.com/products/" 

![selection_502](https://cloud.githubusercontent.com/assets/11461914/18509701/a0791400-7a97-11e6-9d66-f8db26d3f787.png)

**Comment by mattwhisenhunt** [comment]
Thanks for the heads up. Looks like this got resolved.
