### ISSUE TITLE
Setting publishAuto and publishOutsideDomain on revision has no effect

### ISSUE THREAD

**Issue by thesmith** [google/google-api-java-client#1027]
When I try to set publishAuto to true and publishOutsideDomain to false on a file (that has the opposite properties), it has no effect.

```java
final Revision written = drive.revisions().update("FILE_ID", "head", new Revision()
        .setPublishAuto(true)
        .setPublishedOutsideDomain(false)
)
        .setFields("id,mimeType,modifiedTime,publishAuto,published,publishedOutsideDomain")
        .execute();
System.out.println(written);

revisions = drive.revisions().list("FILE_ID")
        .setFields("nextPageToken,revisions(id,mimeType,modifiedTime,publishAuto,published,publishedOutsideDomain)")
        .execute();

final Revision updated = Iterables.getLast(revisions.getRevisions());
System.out.println(updated);
assertTrue(updated.getPublishAuto());
assertFalse(updated.getPublishedOutsideDomain());
```

The asserts fail.

**Comment by mattwhisenhunt** [comment]
This issue may no longer be relevant due to its age. Feel free to re-open.

**Comment by thesmith** [comment]
@mattwhisenhunt but no-one ever looked at it. Want me to confirm it's still an issue or what?

**Comment by mattwhisenhunt** [comment]
@thesmith Thanks for reporting this. I was able to reproduce it today in Java and PHP, which made me think it was an API bug not a client bug… and sure enough it looks like other people are having that same problem: https://issuetracker.google.com/issues/36760086
