### ISSUE TITLE
The field of webContentLink is not returned after changing permission to be anyone

### ISSUE THREAD

**Issue by wangbourne** [google/google-api-java-client#1030]
What i have done is:

step1: change permission:

```
Permission userPermission = new Permission()
                .setType("anyone")
                .setRole("reader");
        driveService.permissions().create(mFileID, userPermission)
                .execute();
```

step2: fetch metadata:

```
File file = driveService.files().get(mFileID).setFields("id, name, webContentLink").execute();
return file.getWebContentLink();
```

However, the truth is there's no field of  WebContentLink. What i can get is only:

![image](https://cloud.githubusercontent.com/assets/2090084/21291865/c674b55e-c53a-11e6-8746-4c159fac8abe.png)

**Comment by mattwhisenhunt** [comment]
This issue may no longer be relevant due to its age. Feel free to re-open.
