### ISSUE TITLE
Depend on newer version of Guava. Guava 17 is more than 2 years old

### ISSUE THREAD

**Issue by tswast** [google/google-api-java-client#1032]
Guava 17 was released on 2014-04-22 according to
https://github.com/google/guava/wiki/ReleaseHistory

I had to start excluding it as a dependency to use the latest version of Guava. https://github.com/GoogleCloudPlatform/java-docs-samples/pull/460/commits/6569349df27296d5f5f60afb4e9a2790c6fd0a34

If the reason the client is using v17 is that it is the latest release that supports JDK5, note that JDK5 has been end-of-life since October 20009. http://www.oracle.com/technetwork/java/eol-135779.html

**Comment by mattwhisenhunt** [comment]
#1070 addressed this issue.
