### ISSUE TITLE
Update developer instructions for Github etc.

### ISSUE THREAD

**Issue by elharo** [google/google-api-java-client#1033]
instructions.html appears out of date. E.g. it still refers to Mercurial and Eclipse 3. Please update.

**Comment by mattwhisenhunt** [comment]
Is this file an artifact from code.google.com? Would it be okay to just remove it?

**Comment by elharo** [comment]
Fine with me, but I don't really know where this file came from or if anyone depends on it. Probably not is my guess.

**Comment by mattwhisenhunt** [comment]
Fixed in #1081
