### ISSUE TITLE
Where can I browse samples ? Like Google Tasks API etc.

### ISSUE THREAD

**Issue by nycodes9** [google/google-api-java-client#1041]
I want to take a look at how Task API are written and developed also other samples are written as pointed here - [Getting Started with the Tasks API and OAuth 2.0 on Android](http://code.google.com/apis/tasks/articles/oauth-and-tasks-on-android.html)

**Comment by mattwhisenhunt** [comment]
https://github.com/google/google-api-java-client-samples
https://developers.google.com/api-client-library/java/google-api-java-client/samples

**Comment by mattwhisenhunt** [comment]
Thank you for filing this issue. We asked some clarifying questions a week or more ago and never heard back from you. We are unable to proceed with this issue until then, so we are closing it. Please feel free to re-open this issue with more information.
