### ISSUE TITLE
Import error - Beginner

### ISSUE THREAD

**Issue by ThallyssonKlein** [google/google-api-java-client#1043]
Hi there. I'm trying to implement the example of the Google Drive API into my Java project. I'm using Maven, and I already imported it:

```
<dependency>
      <groupId>com.google.apis</groupId>
      <artifactId>google-api-services-drive</artifactId>
      <version>v3-rev64-1.22.0</version>
    </dependency>
```

![captura de tela 38](https://cloud.githubusercontent.com/assets/16887598/24125168/10119692-0da6-11e7-876e-baf635d4a97a.png)

Somebody can to help me?

**Comment by mattwhisenhunt** [comment]
Even when you have the entry in pom.xml most IDEs need you to go find the jar file and add the IDE's dependency list.

What IDE is that a screenshot of?

**Comment by ThallyssonKlein** [comment]
I'm sorry, I stopped developing this project but I forgot to close this issue. I've never been able to solve this problem, but I stopped developing the project.
