### ISSUE TITLE
android having problem when i am using framelayout for fragment youtube player

### ISSUE THREAD

**Issue by rahmamajed** [google/google-api-java-client#1047]
i have this error out of unknown
please note that i discard all views on my xml and i am getting this error over and over again even of the xml having just framelayout to display youtube fragment

YouTubeAndroidPlayerAPI: YouTube video playback stopped due to unauthorized overlay on top of player. The YouTubePlayerView is obscured by com.google.android.youtube.player.YouTubePlayerView{1aa23167 V.E..... ........ 0,0-1080,607}. YouTubePlayerView is completely covered, with the distance in px between each edge of the obscuring view and the YouTubePlayerView being: left: 0, top: 0, right: 0, bottom: 0..

please help me it happend to me in two fragment and i am discarding all xml views i just put framelayout

**Comment by mattwhisenhunt** [comment]
Have you found an answer to your question? I am not seeing the connection to api-client. Please include more details and a code snippet if you are still having a problem.

**Comment by mattwhisenhunt** [comment]
Thank you for filing this issue. We asked some clarifying questions a week or more ago and never heard back from you. We are unable to proceed with this issue until then, so we are closing it. Please feel free to comment with more information and we will re-open this issue.
