### ISSUE TITLE
AbstractGoogleClient warns about application name not being set

### ISSUE THREAD

**Issue by meltsufin** [google/google-api-java-client#1062]
I'm hitting this problem by using `SQLAdmin` with the builder, without setting application name by calling `SQLAdmin.Builder(...).setApplicationName("app-name")`, you'll see a warning coming from `AbstractGoogleClient` saying:

"Application name is not set. Call Builder#setApplicationName."

What's the purpose of setting application name? I don't see it being documented. If it's not needed, the warning should be removed.

**Comment by NicolaSpreafico** [comment]
The purpose of settig the application name can be understood by the javadoc
https://google.github.io/google-api-java-client/releases/1.21.0/javadoc/com/google/api/client/googleapis/services/AbstractGoogleClient.Builder.html#setApplicationName(java.lang.String)

> Sets the application name to be used in the UserAgent header of each request or null for none.

**Comment by meltsufin** [comment]
Thanks @NicolaSpreafico for the pointer. The javadoc still doesn't explain why it's important to set it. It might be used for metrics, but as an API user, how does it affect me?
@garrettjonesgoogle PTAL

**Comment by mattwhisenhunt** [comment]
This doesn't really affect you. In general API providers use that header to do all sorts of things and it is not uncommon for it to be required by REST APIs.
