### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by NicolaSpreafico** [google/google-api-java-client#1068]
I saw from Maven release that version 1.23 is out.
Is there any changelog available to understand the differences between 1.22 and 1.23?

**Comment by mattwhisenhunt** [comment]
I know in the past that is something that usually happened on the blog: http://google-api-java-client.blogspot.com/ and I am going see about starting that back up for the next release.

I tend to prefer the command line for these sorts of things:
git log 1.22.0..1.23.0
git diff 1.22.0..1.23.0

But if you know a repo’s tags you can craft a custom URL on Github too:
https://github.com/google/google-api-java-client/compare/1.21.0...1.23.0
