### ISSUE TITLE
Typo in com.google.api.client.auth.openidconnect.IdTokenVerifier.Builder

### ISSUE THREAD

**Issue by merhoo** [google/google-api-java-client#1076]
`Exception in thread "main" java.lang.NoSuchMethodError: com.google.api.client.auth.openidconnect.IdTokenVerifier$Builder.setIssuers(Ljava/util/Collection;)Lcom/google/api/client/auth/openidconnect/IdTokenVerifier$Builder;`

In IDTokenVerifier.Builder, there is a method called setIssuer

So I think that someone accidentally put setIssuers

**Comment by mattwhisenhunt** [comment]
It looks like IdTokenVerifier.Builder has both methods. In fact, this sounds more like a dependency problem. What causes this error for you?

**Comment by mattwhisenhunt** [comment]
Thank you for filing this issue. We asked some clarifying questions a week or more ago and never heard back from you. We are unable to proceed with this issue until then, so we are closing it. Please feel free to re-open this issue with more information.

**Comment by letanloc1998** [comment]
I have same problem. Does any way to fix it?

**Comment by letanloc1998** [comment]
When I debug
I see `com.google.api.client.googleapis.auth.oauth2.GoogleIdTokenVerifier.Builder.setIssuers(Collection<String> issuers)` can't call parent class

**Comment by letanloc1998** [comment]
`com.google.api.client.googleapis.auth.oauth2.GoogleIdTokenVerifier.Builder.setIssuers(Collection<String> issuers)`

```java
    @Override
    public Builder setIssuers(Collection<String> issuers) {
      return (Builder) super.setIssuers(issuers);
    }
```
