### ISSUE TITLE
Some events are simply not returned

### ISSUE THREAD

**Issue by robert4os** [google/google-api-java-client#1077]
For instance for calendar b6iujjbc5glp48t2ltuia48jm0@group.calendar.google.com
...the events on 2018 January 26

On this day events can be seen and edited through the browser app, but they are not retrieved either with:
- java api 3-rev270-1.23.0 nor
- though the api explorer

I have noted this when a program that worked for years began to fail. The problem has started in the last 3-6 weeks.

**Comment by mattwhisenhunt** [comment]
It sounds like it could be a problem with the API if you reproduced it with this client and API Explorer. I searched Google Calendar's [issue tracker](https://issuetracker.google.com/issues?q=componentid:191627%20status:open) and I can't find a reported issue similar to this one that you describe. I would ask, if you do file a bug report there, to please follow the instructions in the description field. Detailed and reproducible bug reports help developers respond quickly to your issue.

**Comment by robert4os** [comment]
Thank you. I have created an issue there. Best regards, Robert

**Comment by robert4os** [comment]
It is working again. Issue can be closed. Thank you
