### ISSUE TITLE
Virus alert on atempt to dowload Gmail API Client Library for Java (zip)

### ISSUE THREAD

**Issue by Litsvin** [google/google-api-java-client#1097]
Hi all!

Today I was trying to download Gmail Api library from here:
https://developers.google.com/api-client-library/java/apis/gmail/v1

and I was promped by my built in Windows Defender that the file I try to download is contaminated with some kind of Trojan virus, which was marked as critical.

Thanks for atention

**Comment by jonparrott** [comment]
@Litsvin acknowledged.

We should do one or more of these:

1. Update the documentation to warn that the zip files may be marked as false positives.
2. See if we can communicate to Windows Defender that this is a false positive.
3. Recommend that users use maven or gradle over downloading a zip.

@Litsvin in the meantime, you should use either maven or gradle to add this to your project.

**Comment by Litsvin** [comment]
@jonparrott , thanks for responce.
I understand following: you're 100% sure there're no viruses, right?))

Also, I'm afraid I cannot use GMail api with maven because in this case I can't build my project - some comflict appears, I assume

**Comment by jonparrott** [comment]
@Litsvin correct, there is not a virus in our client library. It is a false positive. If it's helpful, we can get you the checksum of the zip on our end.

> Also, I'm afraid I cannot use GMail api with maven because in this case I can't build my project - some comflict appears, I assume

If you let us know what the error is, we can possibly help you if you want to try to use maven/gradle.
