### ISSUE TITLE
Datastore examples

### ISSUE THREAD

**Issue by mcantrell** [google/google-api-java-client#1098]
Are there any documented usages for the datastore client? 

     https://developers.google.com/api-client-library/java/apis/datastore/v1

I'm looking for something similar to the quick start for the new version of the client lib.

    https://cloud.google.com/datastore/docs/reference/libraries#using_the_client_library

I've been unsuccessful in finding anything other than references to the new version anywhere.

**Comment by mattwhisenhunt** [comment]
No, datastore samples for this library were never created. GCP is the library to use to start a Datastore project today.

**Comment by nawaf4** [comment]
G
