### ISSUE TITLE
GoogleAuthorizationCodeFlow ends up using App Engine standard env API on App Engine flexible env?

### ISSUE THREAD

**Issue by chanseokoh** [google/google-api-java-client#1105]
A user hit an issue when trying to migrate from "vm: true" to "env: flex": https://stackoverflow.com/q/49521435/1701388

The exception the user got is clearly a standard env API one: `com.google.apphosting.api.ApiProxy$CallNotFoundException`

It is no wonder it says the error message about not doing threading properly on the standard env, which doesn't apply at all on flex: `Can't make API call urlfetch.Fetch in a thread that is neither the original request thread nor a thread created by ThreadManager`

Surprisingly, using a different `GoogleAuthorizationCodeFlow.Builder` constructor worked as a workaround. It seems that the following constructor accepting `GoogleClientSecrets` ends up using a standard API on flex somehow?

```java
    public Builder(HttpTransport transport, JsonFactory jsonFactory,
        GoogleClientSecrets clientSecrets, Collection<String> scopes) {
```

**Comment by rjborba** [comment]
I've update the answer. I just saw here that I made another change besides NOT use GoogleClientSecrets object.

```
private static final HttpTransport HTTP_TRANSPORT = new NetHttpTransport();
private static final UrlFetchTransport HTTP_TRANSPORT = new UrlFetchTransport();

```

Using UrlFetchTransport instead of NetHttpTransport was the truly reason of stacktrace shown.

**Comment by chanseokoh** [comment]
Thanks for the update @rjborba. This is still puzzling to me. URL fetch is a standard env thing and should nothing to do with flexible.

https://cloud.google.com/appengine/docs/flexible/java/migrating#url_fetch

**Comment by chanseokoh** [comment]
Ah, you're saying you were suing URL fetch on flex. Yeah, that is not going to work. Closing this issue.

**Comment by rjborba** [comment]
Yeah.. Sorry about that.

But don`t you think that is supposed to be more clear on docs?

**Comment by chanseokoh** [comment]
@rjborba note that, if you see any official doc is unclear, you can always send your feedback by clicking on the "Send Feedback" button at the bottom of such docs. You may start with the page: https://cloud.google.com/appengine/docs/flexible/java/migrating#url_fetch
