### ISSUE TITLE
Get access token after client authorization

### ISSUE THREAD

**Issue by goxr3plus** [google/google-api-java-client#1119]
> Hi i am building a JavaFX application for Google Drive with basic functionality as (download,upload etc).
> I am using JavaFX Browser for user Authentication , so i can navigate to the URL and then get the html code .

**1)I need to get the Authentication URL
2)I will authenticate with JavaFX Browser , so my question is :
         -> is the access token shown on the html code?**

How to figure the method ```authorize``` of [DriveSample](https://github.com/google/google-api-java-client-samples/blob/master/drive-cmdline-sample/src/main/java/com/google/api/services/samples/drive/cmdline/DriveSample.java) to return me the Authentication URL : 

```JAVA
 /**
   * Authorizes the installed application to access user's protected data.
   */
  private static Credential authorize() throws Exception {
    // load client secrets
    GoogleClientSecrets clientSecrets = GoogleClientSecrets.load(JSON_FACTORY,
        new InputStreamReader(DriveSample.class.getResourceAsStream("/client_secrets.json")));
    if (clientSecrets.getDetails().getClientId().startsWith("Enter")
        || clientSecrets.getDetails().getClientSecret().startsWith("Enter ")) {
      System.out.println(
          "Enter Client ID and Secret from https://code.google.com/apis/console/?api=drive "
              + "into drive-cmdline-sample/src/main/resources/client_secrets.json");
      System.exit(1);
    }
    // set up authorization code flow
    GoogleAuthorizationCodeFlow flow = new GoogleAuthorizationCodeFlow.Builder(httpTransport,
        JSON_FACTORY, clientSecrets, Collections.singleton(DriveScopes.DRIVE_FILE))
            .setDataStoreFactory(dataStoreFactory).build();

    // authorize
    return new AuthorizationCodeInstalledApp(flow, new LocalServerReceiver()).authorize("user");

  }
```

**Comment by goxr3plus** [comment]
It says Please open the following address in your browser: , well i want to open it on my own browser i have created . How i can get it ?

**Comment by chingor13** [comment]
In the next version of google-oauth-java-client (1.25.x), we are adding a `AuthorizedCodeInstalledApp.Browser` interface that you can use to write your own implementation. The default implementation will continue to open the default browser. See https://github.com/google/google-oauth-java-client/pull/182/files

**Comment by myana-mahesh** [comment]
> 
> 
> It says Please open the following address in your browser: , well i want to open it on my own browser i have created . How i can get it ?
> 
> jetty-6.1.x is opening the default web browser .

hey did you found the solution for this problem?
I'm facing the same problem it console logs: Please open this url in your browser,
but i want it to open browser automatically

**Comment by goxr3plus** [comment]
@myana-mahesh  Sorry it's been time i don't even remember if i found the solution lot of stuff has changed since then :)

**Comment by myana-mahesh** [comment]
> @myana-mahesh Sorry it's been time i don't even remember if i found the solution lot of stuff has changed since then :)

No problem.
I found the solution, it occurred because of headless system of spring boot

**Comment by ZChen143** [comment]
> > @myana-mahesh Sorry it's been time i don't even remember if i found the solution lot of stuff has changed since then :)
> 
> No problem.
> I found the solution, it occurred because of headless system of spring boot
Could you share the solution, I met the same problem.

**Comment by ZChen143** [comment]
> > @myana-mahesh Sorry it's been time i don't even remember if i found the solution lot of stuff has changed since then :)
> 
> No problem.
> I found the solution, it occurred because of headless system of spring boot

Could you share the solution, I met the same problem.

**Comment by myana-mahesh** [comment]
problem occurred because of headless system of spring boot,
headless system's can't open browser
so use this below code to set headless false in spring boot 

public static void main(String[] args) {
    SpringApplicationBuilder builder = new SpringApplicationBuilder(App.class);
    builder.headless(false).run(args);
  }

**Comment by ZChen143** [comment]
> problem occurred because of headless system of spring boot,
> headless system's can't open browser
> so use this below code to set headless false in spring boot
> 
> public static void main(String[] args) {
> SpringApplicationBuilder builder = new SpringApplicationBuilder(App.class);
> builder.headless(false).run(args);
> }

Thank you very much, very helpful!
