### ISSUE TITLE
getPlaylistId() is null

### ISSUE THREAD

**Issue by Artuto** [google/google-api-java-client#1121]
What the title says, I'm doing this

```java
if(rId.getKind().equals("youtube#playlist"))
    sb.append(":file_folder: **https://youtube.com/playlist?list=").append(rId.getPlaylistId()).append("**");
```

And it ends on `youtube.com/playlist?list=null`

**Comment by Artuto** [comment]
Will this be fixed soon?

**Comment by chingor13** [comment]
@Artuto Which API endpoint are you trying to use? Are you able to able to reproduce the query that has a null `playlistId` field? What class is `rId`?

**Comment by Artuto** [comment]
https://github.com/EndlessBot/Endless/blob/master/src/main/java/me/artuto/endless/commands/utils/YouTubeCmd.java#L70-L93

**Comment by chingor13** [comment]
@Artuto You're excluding the `id/playlistId` field when asking for data to be returned [here](https://github.com/EndlessBot/Endless/blob/cf5c61f03d794131a67fbe0be8da68b3cb5ac4e2/src/main/java/me/artuto/endless/commands/utils/YouTubeCmd.java#L74).
