### ISSUE TITLE
Google Play error 500 on execute - Replying a Review 

### ISSUE THREAD

**Issue by leonardoviragine** [google/google-api-java-client#1134]
I'm getting the following error on execute():

{
    "error": {
        "code": 500,
        "message": null
    }
}

I'm trying to post a reply in a specific review.. very simple code..credentials are ok (I can get the reviews)

Any advice?

**Comment by chingor13** [comment]
@leonardoviragine Can you post a small snippet to help us try an reproduce this?

**Comment by leonardoviragine** [comment]
Hi. A simple POST, as [ docs says](https://developers.google.com/android-publisher/api-ref/reviews/reply) will return the error:
 (all parameters are sensitive data)

{
    "error": {
        "code": 500,
        "message": null
    }
}

and if I change or ommit any parameter I get a different error code (so I believe there's nothing wrong with my  original call)

I saw [this error ](https://stackoverflow.com/questions/43445821/google-play-rest-api-returning-error-500-while-replying-to-review) on SO and says about getting and replying reviews older than 7 days.. but this is not the case here. (I'm able to get all reviews, no problems on permissions and authentications.

**Comment by leonardoviragine** [comment]
Just updating....

today I run my tests again an no error 500..I guess it's ok now
