### ISSUE TITLE
Directory API - members get 400

### ISSUE THREAD

**Issue by netp-dany** [google/google-api-java-client#1139]
The following request in java 

`directory.members().get(group, email).execute();`

will sometimes get response 400 Invalid Input.
Both group and email belong to the same domain.

I was able to reproduce this with API explorer on this page
https://developers.google.com/admin-sdk/directory/v1/reference/members/get 

This is not constant issue, sometimes it will not occur at all and 200 response would be returned.
It looks as if there is one (or more than one) faulty instance behind load balancer that returns 400 response.

We started to notice that issue on 31st July 2018.

**Comment by chingor13** [comment]
@netp-dany Thanks for letting us know
