### ISSUE TITLE
HttpError 400 in jobs.get(jobId,ProjectId) even with right values.

### ISSUE THREAD

**Issue by wonderfly** [google/google-api-java-client#684]
_From [eladv...@gmail.com](https://code.google.com/u/109464988078552275287/) on December 03, 2012 07:49:41_

when I call jobs.get(jobId,ProjectID);
I get:
 "code" : 400,
  "errors" : [ {
    "domain" : "global",
    "message" : "Invalid project ID 'My_Project_ID:job_6c2e8cc358ad42d2ad55ef266d342b68'. Project IDs must contain 6-63 lowercase letters, digits, or dashes. IDs must start with a letter and may not end with a dash.",
    "reason" : "invalid"
  } ],
  "message" : "Invalid project ID 'My_Project_ID:job_6c2e8cc358ad42d2ad55ef266d342b68'. Project IDs must contain 6-63 lowercase letters, digits, or dashes. IDs must start with a letter and may not end with a dash."

(I switched projectId with "My_Project_ID")

If I use the exact projectID and jobID in the "try it" section in the google developer guide in here: https://developers.google.com/bigquery/docs/reference/v2/jobs/get I get the job back as expected!

If projectId or jobId wasn't right then it wouldn't have worked in the google developer site also.
What can cause this behavior?

_Original issue: http://code.google.com/p/google-api-java-client/issues/detail?id=670_

**Comment by quentin-sommer** [comment]
Hi,

I'm running into this exact issue (the web example also work for me)

Any news?

@wonderfly

**Comment by quentin-sommer** [comment]
@garrettjonesgoogle Who should I mention / where should I post this?
