### ISSUE TITLE
Upload to YouTube fails with java.io.IOException: insufficient data written, but video still appears on YouTube

### ISSUE THREAD

**Issue by wonderfly** [google/google-api-java-client#775]
_From [jlau...@whosay.com](https://code.google.com/u/101051496477945736092/) on April 25, 2013 07:43:30_

Version of google-api-java-client (e.g. 1.5.0-beta)? 1.13.2-beta Java environment (e.g. Java 6, Android 2.3, App Engine)? Java 6 (Linux) Describe the problem. Occasionally when uploading videos to YouTube using API v3, the call to insert(...).execute() will fail with an IOException claiming that not all of the data was written, but the video still appears on YouTube as if it was uploaded successfully. Most of the time the same code works as expected with no exception.

The call being made is as follows:

``` java
youTube.videos().insert(
    "snippet,status",
    video,
    new InputStreamContent(
        mimeType,
        inputStream)
        .setLength(fileSize))
    .execute();
```

How would you expect it to be fixed? The call should not except.

_Original issue: http://code.google.com/p/google-api-java-client/issues/detail?id=774_

**Comment by medaminebh** [comment]
http://stackoverflow.com/a/30796105/4576135
