### ISSUE TITLE
Return value has been changed from java.util.List to java.lang.Object on directory_v1-rev35

### ISSUE THREAD

**Issue by wonderfly** [google/google-api-java-client#884]
_From [u...@gluegent.com](https://code.google.com/u/100492338523862362118/) on June 09, 2014 23:28:52_

Version of google-api-java-client (e.g. 1.15.0-rc)? 1.17.0-rc, 1.18.0-rc
com.google.apis:google-api-services-admin-directory:directory_v1-rev35 Java environment (e.g. Java 6, Android 2.3, App Engine)? Any. Describe the problem. Return Value was java.util.List<SpecificObject> on rev34 but it is Object on rev35.
ex. com.google.api.services.admin.directory.model.User#getAddresses()
 rev34: java.util.List<com.google.api.services.admin.directory.model.UserAddress>
 rev35: java.lang.Object How would you expect it to be fixed? Please undo rev35's specification.

_Original issue: http://code.google.com/p/google-api-java-client/issues/detail?id=884_

**Comment by komasoftware** [comment]
directory_v1-rev62-1.21 and still the same problem

**Comment by komasoftware** [comment]
The best workaround at this time, is to parse the lists with a generic method :

```
public <T extends GenericJson> List<T> parse(Object genericItem, Class<T> clazz){
     List<T> result = new ArrayList<T>();
     if (genericItem != null){
         try {
             Constructor<T> constructor = clazz.getConstructor(new Class[0]);    // find the default constructor of the input class type
             List<ArrayMap<String,Object>> objects = (List<ArrayMap<String,Object>>)genericItem;
             for (ArrayMap<String,Object> object: objects){
                T id = constructor.newInstance(); // call the default constructor
                for (int i = 0; i < object.size(); i++)
                    id.put(object.getKey(i), object.getValue(i));
                result.add(id);
            }
        } catch (NoSuchMethodException ex) {
               Logger.getLogger(ListArrayMapParser.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SecurityException ex) {
            Logger.getLogger(ListArrayMapParser.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(ListArrayMapParser.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(ListArrayMapParser.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalArgumentException ex) {
            Logger.getLogger(ListArrayMapParser.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InvocationTargetException ex) {
            Logger.getLogger(ListArrayMapParser.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    return result;
}
```

see also http://stackoverflow.com/questions/24625322/google-admin-sdk-directory-users-how-to-get-user-phone-numbers-using-java-clie
