### ISSUE TITLE
Update guava dependencies

### ISSUE THREAD

**Issue by wonderfly** [google/google-api-java-client#903]
_From [unify...@gmail.com](https://code.google.com/u/103663392415746357204/) on September 10, 2014 11:27:48_

Version of google-api-java-client 1.19.0

Java environment Java 7, App Engine Describe the problem. There's currently a very old dependency to guava jdk5 version. This is limiting as it conflicts with newer versions. This prevents the use of FluentIterator as it is missing useful methods How would you expect it to be fixed? Update dependency to guava  17.0

_Original issue: http://code.google.com/p/google-api-java-client/issues/detail?id=903_

**Comment by patrickbkelly** [comment]
This also causes a conflict with the gcs-client (cloud storage).

[INFO] +- com.google.apis:google-api-services-drive:jar:v2-rev171-1.20.0:compile
[INFO] |  \- com.google.api-client:google-api-client:jar:1.20.0:compile
[INFO] |     \- com.google.guava:guava-jdk5:jar:13.0:compile
[INFO] \- com.google.appengine.tools:appengine-gcs-client:jar:RELEASE:compile
[INFO]    \- (com.google.guava:guava:jar:18.0:compile - omitted for duplicate)

**Comment by ejona86** [comment]
Is the issue here that the API client depends on guava-jdk5 instead of (vanilla) guava? If so, then even upgrading to guava-jdk5 17 from v13 wouldn't solve the issue. We would either need a separate jdk6+ artifact or drop the jdk5 dependency.

**Comment by krico** [comment]
:+1:

**Comment by nightscape** [comment]
Just ran into this as well. As many libraries are at guava 18 already, this makes it impossible to use google-api-java-client and many other third party libraries together...

**Comment by nightscape** [comment]
I just saw that an update to Guava 17 was already merged in https://github.com/google/google-api-java-client/pull/977
It would be great if you could publish 1.21.0 on Maven central.

**Comment by ejona86** [comment]
The update to Guava 17 didn't actually change any compatibility. Both Maven and Gradle allow you to override the guava-jdk dependency for a normal Guava 18 dependency.

**Comment by ashughes** [comment]
For Android apps that use Guava already (e.g. Guava 18 or 19) and are just now adding a dependency for the google-api-java-client (e.g. through Google Cloud Endpoints), what's the correct/safe way to handle this?

For example, should we just exclude the Guava dependency in google-api-java-client?

    compile (project(path: ':backend', configuration: 'android-endpoints')) {
        exclude group: 'com.google.guava'
    }

Not doing the above causes compile time errors because both the jdk5 version of Guava and normal Guava are included in the project. However, is it "safe" to simply upgrade the version of Guava that the google-api-java-client depends on?

**Comment by ejona86** [comment]
@ashughes, excluding guava-jdk5 is fine. I think it would work fine on 18 and 19. I'd have to compile with 18/19 to double-check, but we use the code with master Guava so even a slightly older release should work fine given Guava's deprecation policy.

**Comment by sefer2** [comment]
This is really awful. In addition to GCS and other Google services, this library conflicts with Google's own "io.grpc:grpc-core" or "io.grpc:grpc-protobuf" because of this Guava dependency here.

> java.lang.NoSuchMethodError: com.google.common.util.concurrent.MoreExecutors.directExecutor()Ljava/util/concurrent/Executor;
> at io.grpc.internal.ClientCallImpl.<init>(ClientCallImpl.java:105)
> at io.grpc.internal.ManagedChannelImpl$RealChannel.newCall(ManagedChannelImpl.java:346)
> at io.grpc.internal.ManagedChannelImpl.newCall(ManagedChannelImpl.java:325)
> at test.GrpcClient$1.interceptCall(GrpcClient.java:111)
> at io.grpc.ClientInterceptors$InterceptorChannel.newCall(ClientInterceptors.java:120)
> at io.grpc.auth.ClientAuthInterceptor.interceptCall(ClientAuthInterceptor.java:79)
> at io.grpc.ClientInterceptors$InterceptorChannel.newCall(ClientInterceptors.java:120)
> at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:129)
> at test.TestServiceGrpc$TestServiceBlockingStub.insert(TestServiceGrpc.java:216)
> at test.GrpcClient.main(GrpcClient.java:163)

We've excluded this dependency explicitly (although we shouldn't need to) and we observed to specific issues that are directly attributed to it, so perhaps it's very easy to upgrade to a newer guava and drop that aging dependency?

Can this dependency be finally dropped? Or perhaps this package split to jdk5 compatible one and jdk6 and newer, which are already most popular by far. But dragging this depenency along breaks other Google package, and that's certainly **not** a good thing. Just my two cents.

Sefer

**Comment by matthewlowry** [comment]
Can confirm works fine with 18. For a Maven project 

```
        <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
            <version>18.0</version>
        </dependency>
        <dependency>
            <groupId>com.google.api-client</groupId>
            <artifactId>google-api-client</artifactId>
            <version>1.21.0</version>
            <exclusions>
                <exclusion>
                    <groupId>com.google.guava</groupId>
                    <artifactId>guava-jdk5</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
```

(needed this because the Elasticsearch client depends on 18 or higher and dies if linked to 17.)

**Comment by sefer2** [comment]
I tried it with 19.0 and it worked for me. I cannot check it right now with 18.0 but I believe it'll probably work as well.

**Comment by iddo** [comment]
The workaround doesn't work for me, I encounter this stack trace:

```
Exception in thread "main" java.lang.NoSuchMethodError: com.google.common.collect.ImmutableSet.of([Ljava/lang/Object;)Lcom/google/common/collect/ImmutableSet;
	at com.google.gdata.wireformats.AltFormat$Builder.setAcceptableTypes(AltFormat.java:399)
	at com.google.gdata.wireformats.AltFormat$Builder.setAcceptableXmlTypes(AltFormat.java:387)
	at com.google.gdata.wireformats.AltFormat.<clinit>(AltFormat.java:49)
	at com.google.gdata.client.Service.<clinit>(Service.java:558)
```
When attempting to create a contact service:

`new ContactsService("app-contactaccessor-1");`

**Comment by matthewlowry** [comment]
@iddo This looks like a stack trace with the old and deprecated `gdata-java-client` library.

`google-api-java-client` is the replacement for it. Seems to me like you need to stop using the old library. Try reading [the migration docs](https://github.com/google/gdata-java-client/blob/wiki/MigratingToGoogleApiJavaClient.md) if you haven't already.

**Comment by iddo** [comment]
@matthewlowry I'm attempting access to the contact service, which seems to have not fully migrated to the new API (write operations are still using the old GData protocol), therefore it relies on the gdata code which, in turn, causes the guava versioning mayhem.
See here https://developers.google.com/google-apps/contacts/v3/:

> Note: For read-only access to users' contacts, use the People API, which provides both contact and profile information, **and does not use the older GData protocol**.

I'm open to any other suggestions you might have.

**Comment by matthewlowry** [comment]
@iddo Hrrmm looks like you are in a bit of a pickle.

Are you using Maven? If so you might be able to use the `maven-shade-plugin` to work around this. Create a project that depends on the `gdata-java-client` library and uses the shade plugin to relocate the old classes in the `com.google.collection` namespace so the old GData library can keep using them without conflicting with the newer Guava classes? No idea if this will work but it would be the next thing I would try.

**Comment by Ronpgo** [comment]
Seriously, still jdk5?
Is there any reason for it.
It still causes problems that everyone using new libraries has to deal with.

**Comment by mattwhisenhunt** [comment]
#1070 addressed this.

**Comment by Kitanotori** [comment]
Release #1070 please.

**Comment by jadekler** [comment]
1.24.1 has been released and includes this fix. `guava-jdk5` is gone, woo!
