### ISSUE TITLE
NoClassFound

### ISSUE THREAD

**Issue by wonderfly** [google/google-api-java-client#921]
_From [rababa...@gmail.com](https://code.google.com/u/100980964980222909224/) on December 10, 2014 22:50:39_

Version of google-api-java-client (e.g. 1.15.0-rc)? Java environment (e.g. Java 6, Android 2.3, App Engine)? Describe the problem. hi all
I tried to use Google Calendar API 3 but error in code without any reasons so this is my code I hope you help me.
and if I use  Google Calendar API 2 also error in link(" http://www.google.com/calendar/feeds/default/allcalendars/full" )

errors happened here " NoClassFound" Please Help me
    //final HttpTransport transport = AndroidHttp.newCompatibleTransport();
    /*final JacksonFactory jsonFactory = new JacksonFactory(); How would you expect it to be fixed?

_Original issue: http://code.google.com/p/google-api-java-client/issues/detail?id=921_

**Comment by mattwhisenhunt** [comment]
This issue may no longer be relevant due to its age. Feel free to re-open.
