### ISSUE TITLE
logging.properties Error

### ISSUE THREAD

**Issue by ricardodenilson** [google/google-api-java-client#929]
I'm using Eclipse to run a Google API code. I´m following this link, http://samples.google-api-java-client.googlecode.com/hg/analytics-cmdline-sample/instructions.html
However, when I try to run the code, I get the following message: "Error: Could not find or load the main class (name of my project).logging.properties"

I did some research and discovered that there is a file (/jre/lib/logging.properties) in my Java installation folder.

Should I edit it? If so, how?

**Comment by mattwhisenhunt** [comment]
This issue may no longer be relevant due to its age. Feel free to re-open.
