### ISSUE TITLE
Google Drive - LIST method doesn't work properly for newly created files in hidden Application Data Folder

### ISSUE THREAD

**Issue by KreoSoft** [google/google-api-java-client#941]
From today Application Data Folder doesn't work properly. I'm using Google Drive Java API to insert JSON files to hidden app data folder. There is no error returned but there is no data in hidden folder. Yesterday it was fine. Also saving files into visible folder works fine. The problem is with hidden app data folder. All my apps used this hidden folder stopped working properly. Please fix this ASAP. Regards.

**Comment by ejona86** [comment]
This issue tracker is for issues with the library itself. Using stackoverflow with the tag google-drive-sdk is more appropriate for this sort of question.
