### ISSUE TITLE
Drive fails with cryptic java.lang.NoSuchField MAJOR_VERSION

### ISSUE THREAD

**Issue by tfmorris** [google/google-api-java-client#942]
The Drive class has a static initializer which does a version check:

```
 static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.20.0 of the Drive API library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }
```

Unfortunately this fails in a rather cryptic fashion if  google-api-client is too old to have this field (1.13.2-beta in my case).  This could be worked around using reflection, but if that's too much trouble, perhaps an entry in the FAQ?

**Comment by mattwhisenhunt** [comment]
Thank you for your feature request. This client library is currently in maintenance mode. We are fixing necessary bugs and adding essential features to ensure this library continues to meet your needs for accessing Google APIs. After careful consideration, we have decided not to proceed with this enhancement. If you disagree, please feel free to re-open this issue and explain why you believe it is essential for users of this client library.

**Comment by tfmorris** [comment]
Thanks for your considered reply of my request (2 1/2 years later).

I withdraw my request for an FAQ entry at this point since I'm sure it's largely, or entirely, irrelevant.

But, just out of curiosity, was the library in "maintenance mode" 2 1/2 years ago?

**Comment by mattwhisenhunt** [comment]
@tfmorris my guess is that there wasn't an exact moment, people changed teams, other projects received more and more focus gradually. I'm fairly new to the scene (3 months) and my role is to make sure the library gets maintenance and doesn't just sit in that mode.
