### ISSUE TITLE
BatchRequest doesn't respond timeously to interrupts

### ISSUE THREAD

**Issue by jamieb22** [google/google-api-java-client#944]
When BatchRequest is busy executing, it cannot be interrupted in a timely fashion.

**Comment by mattwhisenhunt** [comment]
Thank you for your feature request. This client library is currently in maintenance mode. We are fixing necessary bugs and adding essential features to ensure this library continues to meet your needs for accessing Google APIs. After careful consideration, we have decided not to proceed with this enhancement. If you disagree, please feel free to re-open this issue and explain why you believe it is essential for users of this client library.
