### ISSUE TITLE
One can't use GoogleCredential.fromStream() to create a GoogleCredential that has scopes.

### ISSUE THREAD

**Issue by stephenrobertson0** [google/google-api-java-client#949]
I created a google service account for accessing Google Shopping, generated a JSON key, then used GoogleCredential.fromStream() to create a GoogleCredential from it. But when I use it I get this response:

Exception in thread "main" com.google.api.client.auth.oauth2.TokenResponseException: 400 Bad Request
{
  "error": "invalid_scope",
  "error_description": "Empty or missing scope not allowed."
}

So I need to now manually build up my GoogleCredential using the Builder, which is not ideal.

**Comment by ccarpita** [comment]
I just ran into the same issue today, and had to extract various bits of code such as `privateKeyFromPkcs8`  in order to work around the fact that `fromStreamServiceAccount` hard-codes scopes to an empty list.  It would be nice if we could get an API like `builderFromStream` or perhaps the scopes list is parsed from the json.

While using a `.p12` file works in development, our secrets management systems don't handle binary data, so plain-text is necessary for security reasons, and thus I was following the `.json` route when I got bitten by this issue.

Using: com.google.api-ads:1.38.0 -- did a search of master and looks like scopes is still hard-coded as empty list.

**Comment by tankchintan** [comment]
@stephenrobertson0 @ccarpita I did this yesterday, I was not facing the same issue that you guys seem to face. Here is my snippet,

```
                HttpTransport httpTransport = GoogleNetHttpTransport.newTrustedTransport();
                
                InputStream inputStream = IOUtils.toInputStream(serviceAccountJson);
                
                GoogleCredential credential = GoogleCredential.fromStream(inputStream, httpTransport, jsonFactory);
                
                credential = credential.createScoped(Collections.singleton(AndroidPublisherScopes.ANDROIDPUBLISHER));
                
                AndroidPublisher androidPublisher = new AndroidPublisher(httpTransport, jsonFactory, credential);
```

This works fine. Of course this is for `AndroidPublisher`, so I am not sure if its an issue with different API.

**Comment by ccarpita** [comment]
In our case, the failure actually occurred within the `fromStream` stack (which issues a refresh token call), so it was unavoidable.  Is it possible that your credentials don't require scoping for some reason?  Also are your credentials a service account type or user type?

**Comment by tankchintan** [comment]
So I am using at least one scope `AndroidPublisherScopes.ANDROIDPUBLISHER`. And the credentials are of type `service_account`.

**Comment by indriesergiu** [comment]
@ccarpita Try using [GoogleCredential.createScoped(scopes)](https://developers.google.com/api-client-library/java/google-api-java-client/reference/1.20.0/com/google/api/client/googleapis/auth/oauth2/GoogleCredential#createScoped(java.util.Collection))

**Comment by mattwhisenhunt** [comment]
This issue may no longer be relevant due to its age. Feel free to re-open.

**Comment by qwertukg** [comment]
@indriesergiu what is `scopes` here? where is list of it? where is example? still have same issue

**Comment by nstdio** [comment]
@qwertukg [scopes](https://developers.google.com/identity/protocols/googlescopes) are designed to give users fine tuned access to Google Cloud Services.

**Comment by mattwhisenhunt** [comment]
If you are building an app that lets your users connect to their own Google services they need to grant your app permission. The set of scopes your app requests will appear to your users as a list of permissions they say yes to the first time they use your app; in your app, the scopes will be a list of URLs (or consts) near the top of your code that you pass into the client constructor.

Here is a list of potential scopes: https://developers.google.com/identity/protocols/googlescopes

**Comment by booi** [comment]
`GoogleCredential.createScoped(...)` worked for me to add scopes to a service account JSON. In many of our cases, we do not want a manual OAuth flow for wholly owned resources.
