### ISSUE TITLE
Maven: Cannot run program "protoc"

### ISSUE THREAD

**Issue by neshkeev** [google/google-api-java-client#954]
I created a branch based on the 1.20.0 tag, go to the root of the application and execute:

```
mvn clean install -DskipTests
```

It fails:

<pre>
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Parent for the Google API Client Library for Java .. SUCCESS [  2.656 s]
[INFO] Google APIs Client Library for Java ................ FAILURE [  0.619 s]
[INFO] Servlet and JDO extensions to the Google API Client Library for Java. SKIPPED
[INFO] Android Platform Extensions to the Google APIs Client Library for Java. SKIPPED
[INFO] Google App Engine extensions to the Google API Client Library for Java. SKIPPED
[INFO] GSON extensions to the Google APIs Client Library for Java SKIPPED
[INFO] Jackson 2 extensions to the Google APIs Client Library for Java SKIPPED
[INFO] Java 6 (and higher) Extensions to the Google API Client Library for Java. SKIPPED
[INFO] Protocol Buffer extensions to the Google APIs Client Library for Java SKIPPED
[INFO] XML extensions to the Google APIs Client Library for Java SKIPPED
[INFO] Assembly for the Google APIs Client Library for Java SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.594 s
[INFO] Finished at: 2015-07-26T00:35:45+04:00
[INFO] Final Memory: 18M/197M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.6:run
(generate-sources) on project google-api-client: An Ant BuildException has occured: 
Execute failed: java.io.IOException: Cannot run program "protoc" 
(in directory "/home/myname/projects/java/google-api-java-client/google-api-client"): 
error=2, No such file or directory -> [Help 1]
</pre>

I didn't manage to find the "protoc" application using yaourt.

My maven and jdk:

<pre>
mvn -v
Apache Maven 3.3.3 (NON-CANONICAL_2015-04-29T11:04:34_root; 2015-04-29T12:04:34+04:00)
Maven home: /opt/maven
Java version: 1.8.0_51, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-openjdk/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.1.2-2-arch", arch: "amd64", family: "unix"
</pre>

**Comment by ejona86** [comment]
Unfortunately, having the `protoc` binary in your PATH is a requirement for building. See https://developers.google.com/api-client-library/java/google-http-java-client/contribute for information on  building protobuf.

**Comment by ejona86** [comment]
Oh, "yaourt". You are an Arch user. Protoc is available in the "protobuf" package, but offhand I don't remember if it _must_ be 2.4 like the documentation describes, or if Arch's current version of 2.6 will work.

**Comment by wonderfly** [comment]
Unfortunately the library contains some protobuf code (mostly in test
though) in 2.4, which won't compile with protoc 2.5 or above.

On Sat, Jul 25, 2015 at 3:15 PM, Eric Anderson <notifications@github.com>
wrote:

> Oh, "yaourt". You are an Arch user. Protoc is available in the "protobuf"
> package, but offhand I don't remember if it *must* be 2.4 like the
> documentation describes, or if Arch's current version of 2.6 will work.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/google/google-api-java-client/issues/954#issuecomment-124905578>
> .
>



-- 
Best,
Daniel

**Comment by neshkeev** [comment]
Ok, I successfully installed protobuf, but I am not able to build the project anyway. When I execute `mvn clean install` against the branch that is based on `the 1.20.0 tag` I get this error:
<pre>
[INFO] 73 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Parent for the Google API Client Library for Java .. SUCCESS [  5.188 s]
[INFO] Google APIs Client Library for Java ................ FAILURE [  8.932 s]
[INFO] Servlet and JDO extensions to the Google API Client Library for Java. SKIPPED
[INFO] Android Platform Extensions to the Google APIs Client Library for Java. SKIPPED
[INFO] Google App Engine extensions to the Google API Client Library for Java. SKIPPED
[INFO] GSON extensions to the Google APIs Client Library for Java SKIPPED
[INFO] Jackson 2 extensions to the Google APIs Client Library for Java SKIPPED
[INFO] Java 6 (and higher) Extensions to the Google API Client Library for Java. SKIPPED
[INFO] Protocol Buffer extensions to the Google APIs Client Library for Java SKIPPED
[INFO] XML extensions to the Google APIs Client Library for Java SKIPPED
[INFO] Assembly for the Google APIs Client Library for Java SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 14.440 s
[INFO] Finished at: 2015-07-26T03:29:12+04:00
[INFO] Final Memory: 27M/205M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.3.2:testCompile
(default-testCompile) on project google-api-client: Compilation failure: Compilation failure:
[ERROR] /home/myname/projects/java/google-api-java-client/google-api-client/target/generated-test-sources/com/google/api/client/googleapis/batch/ErrorOutput.java:
[215,37] error: cannot find symbol
</pre>
It seems to me that maven either doesn't execute the `maven-antrun-plugin` plugin or the plugin's configuration is wrong.

When I execute `mvn clean install` against the `dev` branch, I get this error:
<pre>
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Parent for the Google API Client Library for Java .. SUCCESS [  3.118 s]
[INFO] Google APIs Client Library for Java ................ FAILURE [  0.146 s]
[INFO] Servlet and JDO extensions to the Google API Client Library for Java. SKIPPED
[INFO] Android Platform Extensions to the Google APIs Client Library for Java. SKIPPED
[INFO] Google App Engine extensions to the Google API Client Library for Java. SKIPPED
[INFO] GSON extensions to the Google APIs Client Library for Java SKIPPED
[INFO] Jackson 2 extensions to the Google APIs Client Library for Java SKIPPED
[INFO] Java 6 (and higher) Extensions to the Google API Client Library for Java. SKIPPED
[INFO] Protocol Buffer extensions to the Google APIs Client Library for Java SKIPPED
[INFO] XML extensions to the Google APIs Client Library for Java SKIPPED
[INFO] Assembly for the Google APIs Client Library for Java SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.665 s
[INFO] Finished at: 2015-07-26T03:42:13+04:00
[INFO] Final Memory: 15M/197M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project google-api-client: 
Could not resolve dependencies for project com.google.api-client:google-api-client:jar:1.21.0-SNAPSHOT: 
The following artifacts could not be resolved: 
com.google.oauth-client:google-oauth-client:jar:1.21.0-SNAPSHOT, 
com.google.http-client:google-http-client-jackson2:jar:1.21.0-SNAPSHOT, 
com.google.http-client:google-http-client-gson:jar:1.21.0-SNAPSHOT,
com.google.http-client:google-http-client-protobuf:jar:1.21.0-SNAPSHOT: 
Failure to find com.google.oauth-client:google-oauth-client:jar:1.21.0-SNAPSHOT 
in https://oss.sonatype.org/content/repositories/snapshots was cached in the local repository,
resolution will not be reattempted until the update interval of sonatype-nexus-snapshots 
has elapsed or updates are forced -> [Help 1]
</pre>

**Comment by ejona86** [comment]
Check the output of your `protoc --version`. It needs to say 2.4.1. Basically, the `protoc` version has to match the version of the protobuf-java runtime, which is defined in the `pom.xml`:
```xml
<project.protobuf-java.version>2.4.1</project.protobuf-java.version>
```

If the `protoc` version doesn't match then you are prone to get random compile errors, like the one you got. Note how the file that failed to be compiled is in the `target/generated-test-sources` directory; it was a generated file.

**Comment by wonderfly** [comment]
For the second error, if you are going to build the google-api-java-client
library from 'dev', you'll need to build its dependencies, i.e.,
google-http-java-client and google-oauth-java-client, from 'dev' first.
-SNAPSHOT versions are only available if you build it locally.

The first error looks like a protobuf/protoc version mismatch to me. Did
you install protoc 2.4.1 as instructed? Check 'protoc --version'.

On Sat, Jul 25, 2015 at 4:45 PM, Nikita Eshkeev <notifications@github.com>
wrote:

> Ok, I successfully installed protobuf, but I am not able to build the
> project anyway. When I execute mvn clean install against the branch that
> is based on the 1.20.0 tag I get this error:
>
> [INFO] 73 errors
> [INFO] -------------------------------------------------------------
> [INFO] ------------------------------------------------------------------------
> [INFO] Reactor Summary:
> [INFO]
> [INFO] Parent for the Google API Client Library for Java .. SUCCESS [  5.188 s]
> [INFO] Google APIs Client Library for Java ................ FAILURE [  8.932 s]
> [INFO] Servlet and JDO extensions to the Google API Client Library for Java. SKIPPED
> [INFO] Android Platform Extensions to the Google APIs Client Library for Java. SKIPPED
> [INFO] Google App Engine extensions to the Google API Client Library for Java. SKIPPED
> [INFO] GSON extensions to the Google APIs Client Library for Java SKIPPED
> [INFO] Jackson 2 extensions to the Google APIs Client Library for Java SKIPPED
> [INFO] Java 6 (and higher) Extensions to the Google API Client Library for Java. SKIPPED
> [INFO] Protocol Buffer extensions to the Google APIs Client Library for Java SKIPPED
> [INFO] XML extensions to the Google APIs Client Library for Java SKIPPED
> [INFO] Assembly for the Google APIs Client Library for Java SKIPPED
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time: 14.440 s
> [INFO] Finished at: 2015-07-26T03:29:12+04:00
> [INFO] Final Memory: 27M/205M
> [INFO] ------------------------------------------------------------------------
> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.3.2:testCompile
> (default-testCompile) on project google-api-client: Compilation failure: Compilation failure:
> [ERROR] /home/myname/projects/java/google-api-java-client/google-api-client/target/generated-test-sources/com/google/api/client/googleapis/batch/ErrorOutput.java:
> [215,37] error: cannot find symbol
>
> It seems to me that maven either doesn't execute the maven-antrun-plugin
> plugin or the plugin's configuration is wrong.
>
> When I execute mvn clean install against the dev branch, I get this error:
>
> [INFO] ------------------------------------------------------------------------
> [INFO] Reactor Summary:
> [INFO]
> [INFO] Parent for the Google API Client Library for Java .. SUCCESS [  3.118 s]
> [INFO] Google APIs Client Library for Java ................ FAILURE [  0.146 s]
> [INFO] Servlet and JDO extensions to the Google API Client Library for Java. SKIPPED
> [INFO] Android Platform Extensions to the Google APIs Client Library for Java. SKIPPED
> [INFO] Google App Engine extensions to the Google API Client Library for Java. SKIPPED
> [INFO] GSON extensions to the Google APIs Client Library for Java SKIPPED
> [INFO] Jackson 2 extensions to the Google APIs Client Library for Java SKIPPED
> [INFO] Java 6 (and higher) Extensions to the Google API Client Library for Java. SKIPPED
> [INFO] Protocol Buffer extensions to the Google APIs Client Library for Java SKIPPED
> [INFO] XML extensions to the Google APIs Client Library for Java SKIPPED
> [INFO] Assembly for the Google APIs Client Library for Java SKIPPED
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time: 3.665 s
> [INFO] Finished at: 2015-07-26T03:42:13+04:00
> [INFO] Final Memory: 15M/197M
> [INFO] ------------------------------------------------------------------------
> [ERROR] Failed to execute goal on project google-api-client:
> Could not resolve dependencies for project com.google.api-client:google-api-client:jar:1.21.0-SNAPSHOT:
> The following artifacts could not be resolved:
> com.google.oauth-client:google-oauth-client:jar:1.21.0-SNAPSHOT,
> com.google.http-client:google-http-client-jackson2:jar:1.21.0-SNAPSHOT,
> com.google.http-client:google-http-client-gson:jar:1.21.0-SNAPSHOT,
> com.google.http-client:google-http-client-protobuf:jar:1.21.0-SNAPSHOT:
> Failure to find com.google.oauth-client:google-oauth-client:jar:1.21.0-SNAPSHOT
> in https://oss.sonatype.org/content/repositories/snapshots was cached in the local repository,
> resolution will not be reattempted until the update interval of sonatype-nexus-snapshots
> has elapsed or updates are forced -> [Help 1]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/google/google-api-java-client/issues/954#issuecomment-124916229>
> .
>



-- 
Best,
Daniel

**Comment by neshkeev** [comment]
Protobuf 2.4.1 is no longer present niether in official repos nor in AUR. I changed 
`<project.protobuf-java.version>2.4.1</project.protobuf-java.version>`
to `<project.protobuf-java.version>2.6.1</project.protobuf-java.version>` in `./pom.xml` but I keep getting the error about the lack of MockData.java and ErrorOutput.java when I execute `mvn clean install` in the branch that is based on the `1.20.0` tag.

**Comment by ejona86** [comment]
Since 2.4 is pretty old and I use proto3 much more frequently, I just build 2.4 as a local version with `./configure --prefix="$HOME/someplace" --disable-shared` and just put it in my PATH when I need it. You could maybe take a look at google/google-http-java-client#295 which is starting to build protoc for Travis-CI.

I just tried and was able to makepkg successfully by taking the [protobuf 2.5 PKGBUILD](https://projects.archlinux.org/svntogit/packages.git/plain/trunk/PKGBUILD?h=packages/protobuf&id=abc09bea84484692f12e9aa4fa8b4b0ab4555bee) and changing the version to 2.4.1 and the md5sum to SKIP.

**Comment by mattwhisenhunt** [comment]
This issue may no longer be relevant due to its age. Feel free to re-open.
