### ISSUE TITLE
Storage sample upload performance is limited by java.util.Random performance

### ISSUE THREAD

**Issue by raggi** [google/google-api-java-client#961]
https://github.com/google/google-api-java-client-samples/blob/master/storage-cmdline-sample/src/main/java/com/google/api/services/samples/storage/cmdline/Helpers.java#L33 cannot keep up with a fast network.

**Comment by raggi** [comment]
Example: 6s for a file read from disk after being created by dd(1) vs. 15s for a file generated via this class.

**Comment by mattwhisenhunt** [comment]
Thank you for your feature request. This client library is currently in maintenance mode. We are fixing necessary bugs and adding essential features to ensure this library continues to meet your needs for accessing Google APIs. After careful consideration, we have decided not to proceed with this enhancement. If you disagree, please feel free to re-open this issue and explain why you believe it is essential for users of this client library.
