### ISSUE TITLE
HOWTO get transaction receipts for Google Play In-App Subscriptions via Google Play Developer API

### ISSUE THREAD

**Issue by tankchintan** [google/google-api-java-client#963]
We have a subscription service that our users can directly subscribe to via Web. But now we are also launching an Android App with enabled Google Play In-App Subscriptions.

So users can subscribe via directly their Android App. Now we need to keep track of this in our backend, so that when users come to the web they should be able to log in & enjoy the content they have subscribed to.

To track whether a user is subscribed or not is fairly trivial by using the [Purchases.subscriptions.get()](https://developers.google.com/android-publisher/api-ref/purchases/subscriptions/get) method.

But we also provide a billing history to the users (which is used in other contexts). Basically we need to know when was a user actually charged for their monthly/yearly dues. On a recurring basis.

My question is, how to get this information? Is it possible to get it via the Play Developer API?

**Comment by sposinff** [comment]
Were you able to discover a solution?

**Comment by tankchintan** [comment]
Yeah (sort of) @sposinff. Please check [here](https://stackoverflow.com/questions/32083155/howto-get-transaction-receipts-for-google-play-in-app-subscriptions-via-google-p)

**Comment by sposinff** [comment]
What about a server-side solution? I have seen
https://developers.google.com/android-publisher/api-ref/purchases/subscriptions,
but I don't see how this gives confirmation of a payment transaction.

**Comment by tankchintan** [comment]
@sposinff yeah there is no direct way (I worked on this about 2 years ago, so I dont know if things have changed after that).

I think the way I worked around it was to check every so often if a particular subscription is still active.

**Comment by sposinff** [comment]
Yep, that is my strategy. It would be nice to know how many transactions
have gone through to match up the finances, but I guess that isn't going to
happen. Thank you.

**Comment by mattwhisenhunt** [comment]
Thanks for raising this issue, I'm sorry I can't seem to find a way to relay this feedback more directly to that particular API team.
