### ISSUE TITLE
Library is very difficult to test due to final classes

### ISSUE THREAD

**Issue by ryber** [google/google-api-java-client#973]
The fact that com.google.api.client.http.HttpRequest and com.google.api.client.http.HttpResponse are marked final makes it very difficult to write any unit tests involving these classes. You cannot mock them or even new one up to use as a stub since their constructors are also package local. This results in developers writing thin wrapper libraries just to get a testable version of the classes.

My preference would be to have interfaces for these classes rather than use the real classes, making them not final would be fine as well

**Comment by dlazerka** [comment]
Vote +1.

**Comment by mattwhisenhunt** [comment]
Thank you for your feature request. This client library is currently in maintenance mode. We are fixing necessary bugs and adding essential features to ensure this library continues to meet your needs for accessing Google APIs. After careful consideration, we have decided not to proceed with this enhancement. If you disagree, please feel free to re-open this issue and explain why you believe it is essential for users of this client library.
