### ISSUE TITLE
translate api client - response doesn't unescaped

### ISSUE THREAD

**Issue by dkBrazz** [google/google-api-java-client#978]
Translate API client doesn't unescape resulted strings.

For example, I am sending `"Hello world" !`
And client returns the string `&quot;Hallo Welt&quot; !`

I believe that if client doing escaping itself, then it should do unescaping too

**Comment by mattwhisenhunt** [comment]
Thank you for your feature request. This client library is currently in maintenance mode. We are fixing necessary bugs and adding essential features to ensure this library continues to meet your needs for accessing Google APIs. After careful consideration, we have decided not to proceed with this enhancement. If you disagree, please feel free to re-open this issue and explain why you believe it is essential for users of this client library.
