### ISSUE TITLE
GoogleCredential.fromStream(JSON_FILE_AS_INPUTSTREAM) is broken

### ISSUE THREAD

**Issue by ics-brettma** [google/google-api-java-client#979]
**Build:** 1.20.0:

`<dependency>
			<groupId>com.google.api-client</groupId>
			<artifactId>google-api-client</artifactId>
			<version>1.20.0</version>
		</dependency>
		<dependency>
			<groupId>com.google.apis</groupId>
			<artifactId>google-api-services-calendar</artifactId>
			<version>v3-rev151-1.20.0</version>
		</dependency>`

Using Google Developer Console I have downloaded a JSON file of my public/private Credentials for my Service Account:

`{
  "private_key_id": "myPrivateKey",
  "private_key": "-----BEGIN PRIVATE KEY-----\myPrivateKeyString\n-----END PRIVATE KEY-----\n",
  "client_email": "myClientEmail@developer.gserviceaccount.com",
  "client_id": "myClientEmailId.apps.googleusercontent.com",
  "type": "service_account"
}`

They are stored on the classpath in a file called `serviceAccountCredentials.json`

When I try to execute the following code to return a GoogleCredential instance:

     `InputStream credentialsJSON = MyClass.class.getClassLoader().getResourceAsStream("serviceAccountCredentials.json");
    JsonFactory JSON_FACTORY = JacksonFactory.getDefaultInstance();
    HttpTransport httpTransport = GoogleNetHttpTransport.newTrustedTransport();
    return GoogleCredential.fromStream(credentialsJSON ,httpTransport,JSON_FACTORY);`

It blows up with **java.lang.IllegalArgumentException: no JSON input found**:

`Exception in thread "main" java.lang.IllegalArgumentException: no JSON input found
    at com.google.api.client.repackaged.com.google.common.base.Preconditions.checkArgument(Preconditions.java:92)
    at com.google.api.client.util.Preconditions.checkArgument(Preconditions.java:49)
    at com.google.api.client.json.JsonParser.startParsing(JsonParser.java:222)
    at com.google.api.client.json.JsonParser.parse(JsonParser.java:379)
    at com.google.api.client.json.JsonParser.parse(JsonParser.java:354)
    at com.google.api.client.json.JsonObjectParser.parseAndClose(JsonObjectParser.java:87)
    at com.google.api.client.json.JsonObjectParser.parseAndClose(JsonObjectParser.java:81)
    at com.google.api.client.googleapis.auth.oauth2.GoogleCredential.fromStream(GoogleCredential.java:250)`

I am able to print the contents of the file to the console using the following code:

`System.out.println(IOUtils.toString(credentialsJSON));`

**Therefore I know that the JSON file is accessible and contains content**.

Popular developer forums are littered with complaints about this method and there is no example of how to use a JSON file for credentials in the documentation.

One assumes therefore that this functionality beginning at line 249 of `GoogleCredential` is broken?

` JsonObjectParser parser = new JsonObjectParser(jsonFactory);`
`GenericJson fileContents = parser.parseAndClose(credentialStream, OAuth2Utils.UTF_8, GenericJson.class);`

**Comment by wonderfly** [comment]
@anthmgoogle

**Comment by anthmgoogle** [comment]
This does look like a bug. I should investigate.

**Comment by ics-brettma** [comment]
GoogleCredential.fromStream(InputStream) was first added in the Jul 2014 v1.19.0 release.

I have re-tested in the following builds and the problem remains right back to its introduction:

1.19.0 - December 2014
1.19.1 - July 2014
1.20.0 - March 2015

I have also retested on both a Linux and a Windows platform and get the same error.

**Comment by ics-brettma** [comment]
@tankchintan On 19th August 2015 [you appear to have got past this issue](https://github.com/google/google-api-java-client/issues/949#issuecomment-132760363) on #949. However in your snippet of code I cannot see how you created your `jsonFactory`. Could you advise?

**Comment by tankchintan** [comment]
@ics-brettma Sure. I did the below,
```
JsonFactory jsonFactory = JacksonFactory.getDefaultInstance();
```

**Comment by ics-brettma** [comment]
@tankchintan Thanks for checking. I have the same configuration. Bizarre that this is a problem for me but it seemed to work for you. I will carry on investigating.

**Comment by ics-brettma** [comment]
Checked dependencies against Google's guidance for generic Java 5+ applications:

`		<dependency>
			<groupId>com.google.api-client</groupId>
			<artifactId>google-api-client</artifactId>
			<version>1.20.0</version>
		</dependency>
		<dependency>
			<groupId>com.google.oauth-client</groupId>
			<artifactId>google-oauth-client</artifactId>
			<version>1.20.0</version>
		</dependency>
		<dependency>
			<groupId>com.google.http-client</groupId>
			<artifactId>google-http-client</artifactId>
			<version>1.20.0</version>
		</dependency>
		<dependency>
			<groupId>com.google.http-client</groupId>
			<artifactId>google-http-client-jackson2</artifactId>
			<version>1.20.0</version>
		</dependency>
		<dependency>
			<groupId>commons-logging</groupId>
			<artifactId>commons-logging</artifactId>
			<version>1.1.1</version>
		</dependency>
		<dependency>
			<groupId>com.google.code.gson</groupId>
			<artifactId>gson</artifactId>
			<version>2.1</version>
		</dependency>
		<dependency>
			<groupId>org.apache.httpcomponents</groupId>
			<artifactId>httpclient</artifactId>
			<version>4.0.1</version>
		</dependency>
		<dependency>
			<groupId>org.apache.httpcomponents</groupId>
			<artifactId>httpcore</artifactId>
			<version>4.0.1</version>
		</dependency>
		<dependency>
			<groupId>org.codehaus.jackson</groupId>
			<artifactId>jackson-core-asl</artifactId>
			<version>1.9.11</version>
		</dependency>
		<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-core</artifactId>
			<version>2.1.3</version>
		</dependency>
		<dependency>
			<groupId>com.google.code.findbugs</groupId>
			<artifactId>jsr305</artifactId>
			<version>1.3.9</version>
		</dependency>
		<dependency>
			<groupId>com.google.protobuf</groupId>
			<artifactId>protobuf-java</artifactId>
			<version>2.4.1</version>
		</dependency>
		<dependency>
			<groupId>org.ogce</groupId>
			<artifactId>xpp3</artifactId>
			<version>1.1.4c</version>
		</dependency>`

Error remains.

**Comment by ics-brettma** [comment]
I've given up - there is definitely an issue here to be fixed.

In the meantime, here is some workaround code which uses Jackson to parse out the JSON manually before building a manual `GoogleCredential` object using an `InputStream` for the service account JSON:

```
private static PrivateKey privateKeyFromPkcs8(String privateKeyPem) throws IOException {
	    Reader reader = new StringReader(privateKeyPem);
	    Section section = PemReader.readFirstSectionAndClose(reader, "PRIVATE KEY");
	    if (section == null) {
	      throw new IOException("Invalid PKCS8 data.");
	    }
	    byte[] bytes = section.getBase64DecodedBytes();
	    PKCS8EncodedKeySpec keySpec = new PKCS8EncodedKeySpec(bytes);
	    Exception unexpectedException = null;
	    try {
	      KeyFactory keyFactory = SecurityUtils.getRsaKeyFactory();
	      PrivateKey privateKey = keyFactory.generatePrivate(keySpec);
	      return privateKey;
	    } catch (NoSuchAlgorithmException exception) {
	      unexpectedException = exception;
	    } catch (InvalidKeySpecException exception) {
	      unexpectedException = exception;
	    }
	    throw new IOException("Unexpected exception reading PKCS data");
	  }
	

	public static GoogleCredential getCredentialInstanceFromStream(InputStream credentialsJSON,
			Set<String> scopes) throws GeneralSecurityException, IOException {

		HashMap result = new ObjectMapper().readValue(
				credentialsJSON, HashMap.class);
		JsonFactory JSON_FACTORY = JacksonFactory.getDefaultInstance();
		HttpTransport httpTransport = GoogleNetHttpTransport
				.newTrustedTransport();
		String clientId = (String) result.get("client_id");
		String clientEmail = (String) result.get("client_email");
		String privateKeyPem = (String) result.get("private_key");
		String privateKeyId = (String) result.get("private_key_id");
		PrivateKey privateKey = privateKeyFromPkcs8(privateKeyPem);
		GoogleCredential credential = new GoogleCredential.Builder()
				.setTransport(httpTransport).setJsonFactory(JSON_FACTORY)
				.setServiceAccountId(clientEmail)
				.setServiceAccountScopes(scopes)
				.setServiceAccountPrivateKey(privateKey)
				.setServiceAccountPrivateKeyId(privateKeyId).build();
		return credential;
	}
```

**Comment by pongad** [comment]
I am not able to reproduce this problem.

My set up is
```
pongad@pongad:~/Desktop/repro/repro-app$ mvn --version
Apache Maven 3.3.3 (7994120775791599e205a5524ec3e0dfe41d4a06; 2015-04-22T04:57:37-07:00)
Maven home: /usr/local/google/home/pongad/oss/apache-maven-3.3.3
Java version: 1.8.0-google-v7, vendor: Google Inc.
Java home: /usr/local/buildtools/java/jdk8-google-v7-64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.13.0-67-generic", arch: "amd64", family: "unix"
```

Reproduction program
```
package com.google.pongad.repro;

import java.io.InputStream;

import com.google.api.client.googleapis.auth.oauth2.GoogleCredential;
import com.google.api.client.googleapis.javanet.GoogleNetHttpTransport;
import com.google.api.client.http.HttpTransport;
import com.google.api.client.json.jackson2.JacksonFactory;
import com.google.api.client.json.JsonFactory;

public class App {
    public static void main(String[] args) throws Exception {
      InputStream credentialsJSON = App.class.getClassLoader().getResourceAsStream("serviceAccountCredentials.json");
      JsonFactory JSON_FACTORY = JacksonFactory.getDefaultInstance();
      HttpTransport httpTransport = GoogleNetHttpTransport.newTrustedTransport();
      GoogleCredential cred = GoogleCredential.fromStream(credentialsJSON, httpTransport, JSON_FACTORY);
      System.out.println(cred.getServiceAccountId());
    }
}
```

Dependencies
```
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.google.pongad.repro</groupId>
  <artifactId>repro-app</artifactId>
  <packaging>jar</packaging>
  <version>1.0-SNAPSHOT</version>
  <name>repro-app</name>
  <url>http://maven.apache.org</url>
  <dependencies>
    <dependency>
      <groupId>com.google.api-client</groupId>
      <artifactId>google-api-client</artifactId>
      <version>1.20.0</version>
    </dependency>
    <dependency>
      <groupId>com.google.apis</groupId>
      <artifactId>google-api-services-calendar</artifactId>
      <version>v3-rev151-1.20.0</version>
    </dependency>
    <dependency>
      <groupId>com.google.http-client</groupId>
      <artifactId>google-http-client-jackson2</artifactId>
      <version>1.20.0</version>
    </dependency>
  </dependencies>
</project>
```

Are we using different setups?
Please also note the steps you took to download the credential JSON file. I'll repeat your step to see if the problem is caused by bad data.

**Comment by ics-brettma** [comment]
@pongad Thanks for looking into this. I am working through this also now. I will replace this comment with my findings.
