### ISSUE TITLE
Release notes

### ISSUE THREAD

**Issue by gabrielittner** [google/google-api-java-client#988]
Are there any release notes available?

This one hasn't been updated since 1.18.0-rc (and for the existing notes all the new features links are broken)
https://developers.google.com/api-client-library/java/google-api-java-client/release-notes

And this one since 1.20.0 
http://google-api-java-client.blogspot.de/

**Comment by ejona86** [comment]
As of yet, no. I'll be posting to http://google-api-java-client.blogspot.com/ eventually. Until then, you can take a look at the [commit log since 1.20.0](https://github.com/google/google-api-java-client/compare/1.20.0...1.21.0), as there weren't too many commits.
