### ISSUE TITLE
Cloud Monitoring: Java Servlet sample has error at https://cloud.google.com/monitoring/api/authentication

### ISSUE THREAD

**Issue by hitstergtd** [google/google-api-java-client#989]
**Description:**
The code for **CloudMonitoringWebServerAuthDemo.java** in the sample code section towards the bottom of page, "**Authorizing the Cloud Monitoring API**", has a small error that must be corrected.

**Location:**
**https://cloud.google.com/monitoring/api/authentication** > Server-side flow > Select _Java Servlet_

**Issue:**
The Class property **METRIC** appears twice. The second property should be called **YOUNGEST**, to match actual call later in the _doGet()_ method, thereby relieving a class compilation error.

**Comment by hitstergtd** [comment]
Anyone from the Google Cloud team had a chance to look at this issue?

**Comment by mattwhisenhunt** [comment]
Thanks for raising this issue. It seems to have been fixed.
