### ISSUE TITLE
drive.files().update broken due to MediaHttpUploader

### ISSUE THREAD

**Issue by planandtrack** [google/google-api-java-client#994]
Trying to update a file in the drive with the current library (drive v3 rev 5) causes an IllegalArgumentException.

This was fixed in https://github.com/google/google-api-java-client/commit/172dfb85fead485163524c190dda0a31836af9c5. However, this commit did not make it into google-api-client-1.21.jar and thus the update() remains broken. Please include a newer version of the api client!

**Comment by sqrrrl** [comment]
+1

**Comment by ottodog** [comment]
+1

**Comment by Maxxan** [comment]
+1

**Comment by jefftharris** [comment]
+1

**Comment by IlyaDvoinoi** [comment]
+1

**Comment by thisischris** [comment]
+1

**Comment by EVIL-SnaKe** [comment]
+1

**Comment by mattwhisenhunt** [comment]
This issue may no longer be relevant due to its age. Feel free to re-open.
